CREATE DATABASE curlydb;
CREATE DATABASE authdb;

CREATE USER user WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE curlydb TO user;
GRANT ALL PRIVILEGES ON DATABASE authdb TO user;
